"""empty message

Revision ID: 140fd561fb75
Revises: f182128e67c4
Create Date: 2026-01-04 16:56:43.774186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140fd561fb75'
down_revision = 'f182128e67c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_subscripcion', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fecha_subscripcion')

    # ### end Alembic commands ###
